[package]
name = "kernel-serial-impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uart_16550 = "0.2.19"
lazy_static = {version = "1.4.0", features = ["spin_no_std"]}
spin = "0.9"
